## Импорты

In [79]:
import pandas as pd
import numpy as np

## Читаем датамсеты делаем маппинг

In [80]:
games = pd.read_csv('data/games.csv')
games['first_release_date'] = pd.to_datetime(games['first_release_date'], unit='s')
games['game_modes'] = games['game_modes'].apply(lambda x: x.replace('[', '').replace(']', '') if pd.notna(x) else x)
games['genres'] = games['genres'].apply(lambda x: x.replace('[', '').replace(']', '') if pd.notna(x) else x)
games['platforms'] = games['platforms'].apply(lambda x: x.replace('[', '').replace(']', '') if pd.notna(x) else x)
games['themes'] = games['themes'].apply(lambda x: x.replace('[', '').replace(']', '') if pd.notna(x) else x)
games.head()

,id,first_release_date,game_modes,genres,name,platforms,rating,summary,themes,total_rating,total_rating_count,game_type,storyline,age_ratings,game_status,aggregated_rating,aggregated_rating_count,hypes
0,376092,2025-10-31,1,32,Silly Survivors,6,100.0,"Silly Survivors - a casual, pared-down rogueli...",1,100.0,6,0,NaN,NaN,NaN,NaN,NaN,NaN
1,330539,2025-04-18,"2, 3, 5","5, 12, 13",Oxide: Survival Island,"34, 39",100.0,OXIDE is a mobile multiplayer survival simulat...,"21, 23, 33, 38",100.0,9,0,"Here you are, alone on the abandoned island, w...",NaN,NaN,NaN,NaN,NaN
2,328386,2025-01-16,NaN,NaN,Rooftop Rascal: The Claus Cat,"48, 167",100.0,"In ""Rooftop Rascal: The Claus Cat,"" take contr...",NaN,100.0,7,0,NaN,[196045],NaN,NaN,NaN,NaN
3,269473,2023-10-06,"1, 2, 3",32,Resonite,"3, 6, 163",100.0,Enter a novel digital universe with infinite p...,"28, 33, 34",100.0,10,0,NaN,NaN,4.0,NaN,NaN,NaN
4,65755,2011-07-29,1,"2, 31",Trailer Park King,12,100.0,"He's a gamer, a bootlegger, a photographer and...",27,100.0,47,0,NaN,NaN,NaN,NaN,NaN,NaN

In [81]:
game_modes = pd.read_csv('data/game_modes.csv')
game_modes_map = dict(zip(game_modes['id'].astype(str), game_modes['name']))
game_modes_map

{'1': 'Single player',
 '2': 'Multiplayer',
 '3': 'Co-operative',
 '4': 'Split screen',
 '5': 'Massively Multiplayer Online (MMO)',
 '6': 'Battle Royale'}

In [82]:
genres = pd.read_csv('data/genres.csv')
genres_map = dict(zip(genres['id'].astype(str), genres['name']))
genres_map

{'2': 'Point-and-click',
 '4': 'Fighting',
 '5': 'Shooter',
 '7': 'Music',
 '8': 'Platform',
 '9': 'Puzzle',
 '10': 'Racing',
 '11': 'Real Time Strategy (RTS)',
 '12': 'Role-playing (RPG)',
 '13': 'Simulator',
 '14': 'Sport',
 '15': 'Strategy',
 '16': 'Turn-based strategy (TBS)',
 '24': 'Tactical',
 '25': "Hack and slash/Beat 'em up",
 '26': 'Quiz/Trivia',
 '30': 'Pinball',
 '31': 'Adventure',
 '32': 'Indie',
 '33': 'Arcade',
 '34': 'Visual Novel',
 '35': 'Card & Board Game',
 '36': 'MOBA'}

In [83]:
platforms = pd.read_csv('data/platforms.csv')
platforms_map = dict(zip(platforms['id'].astype(str), platforms['name']))
platforms_map

{'376': 'Epoch Super Cassette Vision',
 '510': 'e-Reader / Card-e Reader',
 '12': 'Xbox 360',
 '32': 'Sega Saturn',
 '62': 'Atari Jaguar',
 '148': 'AY-3-8607',
 '150': 'Turbografx-16/PC Engine CD',
 '156': 'Thomson MO5',
 '306': 'Satellaview',
 '339': 'Sega Pico',
 '389': 'AirConsole',
 '13': 'DOS',
 '60': 'Atari 7800',
 '41': 'Wii U',
 '309': 'Evercade',
 '506': 'Amstrad GX4000',
 '112': 'Microcomputer',
 '410': 'Atari Jaguar CD',
 '30': 'Sega 32X',
 '53': 'MSX2',
 '61': 'Atari Lynx',
 '77': 'Sharp X1',
 '120': 'Neo Geo Pocket Color',
 '127': 'Fairchild Channel F',
 '132': 'Amazon Fire TV',
 '413': 'Leapster Explorer/LeadPad Explorer',
 '140': 'AY-3-8500',
 '143': 'AY-3-8760',
 '153': 'Dragon 32/64',
 '167': 'PlayStation 5',
 '154': 'Amstrad PCW',
 '70': 'Vectrex',
 '87': 'Virtual Boy',
 '145': 'AY-3-8603',
 '386': 'Meta Quest 2',
 '390': 'PlayStation VR2',
 '477': 'Panasonic Jungle',
 '65': 'Atari 8-bit',
 '158': 'Commodore CDTV',
 '165': 'PlayStation VR',
 '504': 'Uzebox',
 '440': 'Visual Memory Unit / Visual Memory System',
 '473': 'Arcadia 2001',
 '474': 'Gizmondo',
 '48': 'PlayStation 4',
 '51': 'Family Computer Disk System',
 '89': 'Microvision',
 '94': 'Commodore Plus/4',
 '123': 'WonderSwan Color',
 '128': 'PC Engine SuperGrafx',
 '129': 'Texas Instruments TI-99',
 '482': 'Sega CD 32X',
 '3': 'Linux',
 '8': 'PlayStation 2',
 '88': 'Odyssey',
 '97': 'PDP-8',
 '23': 'Dreamcast',
 '136': 'Neo Geo CD',
 '134': 'Acorn Electron',
 '35': 'Sega Game Gear',
 '39': 'iOS',
 '44': 'Tapwave Zodiac',
 '6': 'PC (Microsoft Windows)',
 '78': 'Sega CD',
 '144': 'AY-3-8710',
 '146': 'AY-3-8605',
 '163': 'SteamVR',
 '373': 'Sinclair ZX81',
 '147': 'AY-3-8606',
 '149': 'PC-9800 Series',
 '237': 'Sol-20',
 '505': 'Elektor TV Games Computer',
 '24': 'Game Boy Advance',
 '72': 'Ouya',
 '85': 'Donner Model 30',
 '115': 'Apple IIGS',
 '119': 'Neo Geo Pocket',
 '125': 'PC-8800 Series',
 '133': 'Odyssey 2 / Videopac G7000',
 '135': 'Hyper Neo Geo 64',
 '142': 'PC-50X Family',
 '9': 'PlayStation 3',
 '98': 'DEC GT40',
 '11': 'Xbox',
 '111': 'Imlac PDS-1',
 '162': 'Oculus VR',
 '20': 'Nintendo DS',
 '18': 'Nintendo Entertainment System',
 '46': 'PlayStation Vita',
 '308': 'Playdia',
 '116': 'Acorn Archimedes',
 '117': 'Philips CD-i',
 '22': 'Game Boy Color',
 '15': 'Commodore C64/128/MAX',
 '101': 'Ferranti Nimrod Computer',
 '67': 'Intellivision',
 '73': 'BlackBerry OS',
 '86': 'TurboGrafx-16/PC Engine',
 '66': 'Atari 5200',
 '108': 'PDP-11',
 '109': 'CDC Cyber 70',
 '113': 'OnLive Game System',
 '118': 'FM Towns',
 '121': 'Sharp X68000',
 '124': 'SwanCrystal',
 '131': 'Super NES CD-ROM System',
 '138': 'VC 4000',
 '139': '1292 Advanced Programmable Video System',
 '152': 'FM-7',
 '155': 'Tatung Einstein',
 '157': 'NEC PC-6000 Series',
 '307': 'Game & Watch',
 '114': 'Amiga CD32',
 '161': 'Windows Mixed Reality',
 '374': 'Sharp MZ-2200',
 '375': 'Epoch Cassette Vision',
 '377': 'Plug & Play',
 '379': 'Game.com',
 '103': 'PDP-7',
 '382': 'Intellivision Amico',
 '384': 'Oculus Quest',
 '385': 'Oculus Rift',
 '387': 'Oculus Go',
 '479': "Terebikko / See 'n Say Video Phone",
 '507': 'Advanced Pico Beena',
 '508': 'Nintendo Switch 2',
 '21': 'Nintendo GameCube',
 '33': 'Game Boy',
 '137': 'New Nintendo 3DS',
 '42': 'N-Gage',
 '57': 'WonderSwan',
 '38': 'PlayStation Portable',
 '69': 'BBC Microcomputer System',
 '71': 'Commodore VIC-20',
 '74': 'Windows Phone',
 '79': 'Neo Geo MVS',
 '80': 'Neo Geo AES',
 '84': 'SG-1000',
 '91': 'Bally Astrocade',
 '93': 'Commodore 16',
 '96': 'PDP-10',
 '122': 'Nuon',
 '141': 'AY-3-8610',
 '170': 'Google Stadia',
 '388': 'Gear VR',
 '372': 'OOParts',
 '203': 'DUPLICATE Stadia',
 '164': 'Daydream',
 '380': 'Casio Loopy',
 '100': 'Analogue electronics',
 '415': 'Watara/QuickShot Supervision',
 '478': 'Panasonic M2',
 '486': 'Digiblast',
 '381': 'Playdate',
 '509': 'Polymega',
 '26': 'ZX Spectrum',
 '378': 'Gamate',
 '27': 'MSX',
 '37': 'Nintendo 3DS',
 '169': 'Xbox Series X|S',
 '64': 'Sega Master System/Mark III',
 '95': 'PDP-1',
 '99': 'Family Computer',
 '102': 'EDSAC',
 '104': 'HP 2100',
 '105': 'HP 3000',
 '106': 'SDS Sigma 7',
 '107': 'Call-A-Computer time-shared mainframe computer system',
 '110': 'PLATO',
 '151': 'TRS-80 Color Computer',
 '166': 'Pokémon mini',
 '50': '3DO Interactive Multiplayer',
 '238': 'DVD Player',
 '239': 'Blu-ray Player',
 '240': 'Zeebo',
 '274': 'PC-FX',
 '411': 'Handheld Electronic LCD',
 '236': 'Exidy Sorcerer',
 '405': 'Windows Mobile',
 '406': 'Sinclair QL',
 '407': 'HyperScan',
 '408': 'Mega Duck/Cougar Boy',
 '409': 'Legacy Computer',
 '412': 'Leapster',
 '414': 'LeapTV',
 '417': 'Palm OS',
 '439': 'V.Smile',
 '441': 'PocketStation',
 '471': 'Meta Quest 3',
 '472': 'visionOS',
 '475': 'R-Zone',
 '476': 'Apple Pippin',
 '480': "Super A'Can",
 '481': 'Tomy Tutor / Pyuta / Grandstand Tutor',
 '34': 'Android',
 '16': 'Amiga',
 '68': 'ColecoVision',
 '25': 'Amstrad CPC',
 '52': 'Arcade',
 '29': 'Sega Mega Drive/Genesis',
 '47': 'Virtual Console',
 '7': 'PlayStation',
 '416': '64DD',
 '438': 'Arduboy',
 '59': 'Atari 2600',
 '55': 'Legacy Mobile Device',
 '159': 'Nintendo DSi',
 '90': 'Commodore PET',
 '126': 'TRS-80',
 '487': 'LaserActive',
 '4': 'Nintendo 64',
 '5': 'Wii',
 '19': 'Super Nintendo Entertainment System',
 '49': 'Xbox One',
 '58': 'Super Famicom',
 '63': 'Atari ST/STE',
 '75': 'Apple II',
 '14': 'Mac',
 '82': 'Web browser',
 '130': 'Nintendo Switch'}

In [84]:
themes = pd.read_csv('data/themes.csv')
themes_map = dict(zip(themes['id'].astype(str), themes['name']))
themes_map

{'31': 'Drama',
 '32': 'Non-fiction',
 '33': 'Sandbox',
 '34': 'Educational',
 '35': 'Kids',
 '38': 'Open world',
 '39': 'Warfare',
 '40': 'Party',
 '41': '4X (explore, expand, exploit, and exterminate)',
 '42': 'Erotic',
 '43': 'Mystery',
 '1': 'Action',
 '17': 'Fantasy',
 '18': 'Science fiction',
 '19': 'Horror',
 '20': 'Thriller',
 '21': 'Survival',
 '22': 'Historical',
 '23': 'Stealth',
 '27': 'Comedy',
 '28': 'Business',
 '44': 'Romance'}

## Заменяем в основном датасете

Делаем функцию для замены

In [85]:
def replace_ids(x, mapping):

    if pd.isna(x):
        return x
    
    col = x.split(', ')
    names = []
    
    for i in col:
        if i in mapping:
            names.append(mapping[i])
        else:
            names.append(i)
    res = ', '.join(names)
    return res

In [86]:

games['game_modes'] = games['game_modes'].apply(replace_ids, mapping=game_modes_map)
games['genres'] = games['genres'].apply(replace_ids, mapping=genres_map)
games['platforms'] = games['platforms'].apply(replace_ids, mapping=platforms_map)
games['themes'] = games['themes'].apply(replace_ids, mapping=themes_map)
games.head()

,id,first_release_date,game_modes,genres,name,platforms,rating,summary,themes,total_rating,total_rating_count,game_type,storyline,age_ratings,game_status,aggregated_rating,aggregated_rating_count,hypes
0,376092,2025-10-31,Single player,Indie,Silly Survivors,PC (Microsoft Windows),100.0,"Silly Survivors - a casual, pared-down rogueli...",Action,100.0,6,0,NaN,NaN,NaN,NaN,NaN,NaN
1,330539,2025-04-18,"Multiplayer, Co-operative, Massively Multiplay...","Shooter, Role-playing (RPG), Simulator",Oxide: Survival Island,"Android, iOS",100.0,OXIDE is a mobile multiplayer survival simulat...,"Survival, Stealth, Sandbox, Open world",100.0,9,0,"Here you are, alone on the abandoned island, w...",NaN,NaN,NaN,NaN,NaN
2,328386,2025-01-16,NaN,NaN,Rooftop Rascal: The Claus Cat,"PlayStation 4, PlayStation 5",100.0,"In ""Rooftop Rascal: The Claus Cat,"" take contr...",NaN,100.0,7,0,NaN,[196045],NaN,NaN,NaN,NaN
3,269473,2023-10-06,"Single player, Multiplayer, Co-operative",Indie,Resonite,"Linux, PC (Microsoft Windows), SteamVR",100.0,Enter a novel digital universe with infinite p...,"Business, Sandbox, Educational",100.0,10,0,NaN,NaN,4.0,NaN,NaN,NaN
4,65755,2011-07-29,Single player,"Point-and-click, Adventure",Trailer Park King,Xbox 360,100.0,"He's a gamer, a bootlegger, a photographer and...",Comedy,100.0,47,0,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
games.to_csv('data/games_complete.csv', index=False)